---
title: "Study 1 Sample Report"
author: "431 Staff"
date: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

A [Sample Study 1 Report](sample-study1.qmd) is now available.

The Sample Study 1 Report provides a brief demonstration of an appropriate analysis for each of the required Study 1 analyses in Project B. Complete instructions for your Study 1 report [are available here](study1b.qmd). 

## The Study 1 Sample Report

The Sample Study 1 Report demonstrates many of the elements you would need to complete, including:

- data ingest and merging
- cleaning the data
- codebook, analytic tibble and data summary
- Analysis A: Compare two means/medians using paired samples
- Analysis B: Compare two means/medians using independent samples
- Analysis C: Compare 3-6 means/medians using independent samples
- Analysis D: Create and analyze a $2 \times 2$ table
- Analysis E: Create and analyze a $J \times K$ table, where $2 \leq J \leq 5$ and $3 \leq K \leq 5$
- Session Information

for a sample of 53 observations (before I drop missing values) from a 2015 class survey of 431 students and TAs from that year. Since the sample size is much smaller than what you will be using, some issues are more problematic here than you might have to deal with in your work.

## Study 1 Sample Report Documents

The [Sample Study 1 Report](sample-study1.qmd) can be viewed in HTML at [this link](sample-study1.qmd). 

There is a link at the top of the HTML document where you can download the complete Quarto code used to create the Sample Study 1 Report, which might be a helpful **template** for your Study 1 report.

The raw data files for the Sample Study 1 Report are described in the Quarto and HTML files above and are found on [the 431-data website](https://github.com/THOMASELOVE/431-data). They are named:

- projectB-study1-demo-survey-2015a.xlsx (first 20 observations, all 21 columns)
- projectB-study1-demo-survey-2015b.csv (remaining 33 observations, some of the 21 columns)
- projectB-study1-demo-survey-2015c.csv (remaining 33 observations, rest of the 21 columns)

The final data set after merging for the Sample Study 1 Report includes 53 observations on 21 columns. The subjects are identified with a code called `s_id` in each of the raw data files.

## Caveats

1. The Sample Study 1 Report does not precisely follow the requirements from Study 1 for the Research Question and Conclusions sections, because that is a big part of your job. 

2. The Sample Study 1 Report has a much smaller data set than you will have, so I don't hold myself in the Sample Study 1 Report to the standards for cell sizes and numbers of observations that you will need to meet in your Study 1.

3. In the Sample Study 1 Report, I produce all 5 analyses (you will do only 4) and I also run several different possible analyses in most cases, when you will instead select one. For instance, in comparing paired samples, the demonstration shows code for confidence intervals based on the t distribution and the bootstrap, while your Project B Study 1 will include just one of these, should you choose to do that analysis. 

4. Outside of those caveats, these demonstrations are meant to be accurate and reflect the level of detail I'm looking for, although it is certainly possible to expand on these demonstrations in your work, if that seems helpful. I believe the Sample Study 1 Report to be largely accurate, but many eyes will find some issues, probably. 

If people find corrections and would be good enough to email me about them I will attempt to reflect those edits in revisions. If I do something in the Sample Study 1 Report that appears to be in conflict with the instructions for Study 1, then (a) please let me know, and (b) treat the Study 1 instructions as your guidepost in completing your work.
